shop:
  defaultMailSenderName: "Test Store"

channels:
  - name: "Test Channel"
    currencyCode: USD
    defaultCountry: US
    slug: test-channel
    isActive: true
    settings:
      useLegacyErrorFlow: true
      automaticallyCompleteFullyPaidCheckouts: false
      defaultTransactionFlowStrategy: CHARGE
      allocationStrategy: PRIORITIZE_HIGH_STOCK
      automaticallyConfirmAllNewOrders: true
      automaticallyFulfillNonShippableGiftCard: true
      expireOrdersAfter: 0
      deleteExpiredOrdersAfter: 60
      markAsPaidStrategy: PAYMENT_FLOW
      allowUnpaidOrders: false
      includeDraftOrderInVoucherUsage: false

categories:
  - name: Test Category A
    slug: test-category-a
  - name: Test Category B
    slug: test-category-b