// This file is generated by scripts/generate-dsl-types.ts

import type { SaleorConfig } from "../modules/config/schema/schema";
import type { CountryCode, CurrencyCode } from "../modules/config/schema/schema";

export type ShopProps = NonNullable<SaleorConfig["shop"]>;
export type ChannelProps = NonNullable<SaleorConfig["channels"]>[number];
export type WarehouseProps = NonNullable<SaleorConfig["warehouses"]>[number];
export type ShippingZoneProps = NonNullable<SaleorConfig["shippingZones"]>[number];
export type TaxClassProps = NonNullable<SaleorConfig["taxClasses"]>[number];
export type AttributeProps = NonNullable<SaleorConfig["attributes"]>[number];
export type ProductTypeProps = NonNullable<SaleorConfig["productTypes"]>[number];
export type PageTypeProps = NonNullable<SaleorConfig["pageTypes"]>[number];
export type ModelTypeProps = NonNullable<SaleorConfig["modelTypes"]>[number];
export type CategoryProps = NonNullable<SaleorConfig["categories"]>[number];
export type CollectionProps = NonNullable<SaleorConfig["collections"]>[number];
export type ProductProps = NonNullable<SaleorConfig["products"]>[number];
export type ProductVariantProps = NonNullable<NonNullable<SaleorConfig["products"]>[number]["variants"]>[number];
export type ModelProps = NonNullable<SaleorConfig["models"]>[number];
export type MenuProps = NonNullable<SaleorConfig["menus"]>[number];

export type { CountryCode, CurrencyCode };
