services:
  api:
    image: ghcr.io/saleor/saleor:3.20
    ports:
      - "8000"  # Dynamic port allocation
    environment:
      DATABASE_URL: "postgresql://saleor:saleor@db/saleor"
      REDIS_URL: "redis://redis:6379/0"
      CELERY_BROKER_URL: "redis://redis:6379/1"
      SECRET_KEY: "test-secret-key-for-e2e-testing"
      DEBUG: "false"
      ALLOWED_HOSTS: "*"
      DEFAULT_FROM_EMAIL: "test@example.com"
      ENABLE_ACCOUNT_CONFIRMATION_BY_EMAIL: "false"
      # Disable unnecessary features for faster startup
      ENABLE_DEBUG_TOOLBAR: "false"
      JAEGER_AGENT_HOST: ""
      # Create default superuser
      CREATE_SUPERUSER: "true"
      SUPERUSER_EMAIL: "admin@example.com"
      SUPERUSER_PASSWORD: "admin123"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/graphql/').raise_for_status()"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    volumes:
      - saleor-media:/app/media

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: saleor
      POSTGRES_PASSWORD: saleor
      POSTGRES_DB: saleor
    volumes:
      - ./seed:/docker-entrypoint-initdb.d:ro
      - saleor-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U saleor"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - saleor-redis:/data

  worker:
    image: ghcr.io/saleor/saleor:3.20
    command: celery -A saleor --app=saleor.celeryconf:app worker --loglevel=info -E
    environment:
      DATABASE_URL: "postgresql://saleor:saleor@db/saleor"
      REDIS_URL: "redis://redis:6379/0"
      CELERY_BROKER_URL: "redis://redis:6379/1"
      SECRET_KEY: "test-secret-key-for-e2e-testing"
    depends_on:
      - api
      - redis
      - db
    volumes:
      - saleor-media:/app/media

volumes:
  saleor-db:
  saleor-redis:
  saleor-media:

networks:
  default:
    name: saleor-e2e-test