import { writeFile } from "node:fs/promises";
import path from "node:path";

const HEADER = `// This file is generated by scripts/generate-dsl-types.ts\n`;

const IMPORTS = `import type { SaleorConfig } from "../modules/config/schema/schema";\nimport type { CountryCode, CurrencyCode } from "../modules/config/schema/schema";\n`;

const BODY = `export type ShopProps = NonNullable<SaleorConfig["shop"]>;\nexport type ChannelProps = NonNullable<SaleorConfig["channels"]>[number];\nexport type WarehouseProps = NonNullable<SaleorConfig["warehouses"]>[number];\nexport type ShippingZoneProps = NonNullable<SaleorConfig["shippingZones"]>[number];\nexport type TaxClassProps = NonNullable<SaleorConfig["taxClasses"]>[number];\nexport type AttributeProps = NonNullable<SaleorConfig["attributes"]>[number];\nexport type ProductTypeProps = NonNullable<SaleorConfig["productTypes"]>[number];\nexport type PageTypeProps = NonNullable<SaleorConfig["pageTypes"]>[number];\nexport type ModelTypeProps = NonNullable<SaleorConfig["modelTypes"]>[number];\nexport type CategoryProps = NonNullable<SaleorConfig["categories"]>[number];\nexport type CollectionProps = NonNullable<SaleorConfig["collections"]>[number];\nexport type ProductProps = NonNullable<SaleorConfig["products"]>[number];\nexport type ProductVariantProps = NonNullable<NonNullable<SaleorConfig["products"]>[number]["variants"]>[number];\nexport type ModelProps = NonNullable<SaleorConfig["models"]>[number];\nexport type MenuProps = NonNullable<SaleorConfig["menus"]>[number];\n\nexport type { CountryCode, CurrencyCode };\n`;

async function main(): Promise<void> {
  const target = path.resolve("src/dsl/types.ts");
  await writeFile(target, `${HEADER}\n${IMPORTS}\n${BODY}`, "utf-8");
}

void main();
